version: '3.8'

services:
  mediawiki:
    image: mediawiki:1.35
    container_name: mediawiki
    ports:
      - "8980:80"  # Map le port 80 du conteneur au port 8080 de la machine hôte
    volumes:
      - mediawiki-data:/var/www/html
    environment:
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=mediawikiuser
      - MEDIAWIKI_DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: mediawiki_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawikiuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Map le port 3306 du conteneur au port 3306 de la machine hôte
    volumes:
      - db-data:/var/lib/mysql

volumes:
  mediawiki-data:
  db-data:
