name: Déployer la documentation sur MediaWiki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Cette étape vérifie le code du dépôt pour que les autres étapes puissent y accéder

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        # Cette étape configure l'environnement Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Cette étape installe les dépendances spécifiées dans requirements.txt

      - name: Build documentation
        run: |
          make html
        # Cette étape construit la documentation (assurez-vous que vous avez un Makefile configuré)

      - name: Deploy to MediaWiki
        env:
          MEDIAWIKI_API_URL: ${{ secrets.MEDIAWIKI_API_URL }}
          MEDIAWIKI_USER: ${{ secrets.MEDIAWIKI_USER }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
        run: |
          python deploy_to_mediawiki.py
        # Cette étape déploie la documentation sur MediaWiki en utilisant un script Python
