name: Deploy Documentation to MediaWiki

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # Ce step vérifie le code du dépôt pour que les autres étapes puissent y accéder

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        # Ce step configure l'environnement Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Ce step installe les dépendances spécifiées dans requirements.txt

      - name: Build Documentation
        run: |
          make html
        # Ce step construit la documentation (assurez-vous que vous avez un Makefile configuré)

      - name: Deploy to MediaWiki
        env:
          MEDIAWIKI_API_URL: ${{ secrets.MEDIAWIKI_API_URL }}
          MEDIAWIKI_USER: ${{ secrets.MEDIAWIKI_USER }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
        run: |
          python deploy_to_mediawiki.py
        # Ce step déploie la documentation sur MediaWiki en utilisant un script Python
